version: '2'
services:
  test:
    build: .
    entrypoint: []
    command: python manage.py test --keepdb
    links:
      # - rabbitmq
      - postgres
      # - memcache
    volumes:
      - .:/usr/src/app
    environment:
      DEBUG: 1
      DATABASE_URL: psql://kompassi:secret@postgres/kompassi
      # BROKER_URL: amqp://guest:guest@rabbitmq/
      # KOMPAQ_URL: amqp://guest:guest@rabbitmq/
      # CACHE_URL: memcache://memcache
      ALLOWED_HOSTS: '*'
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kompassi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kompassi
volumes:
  postgres-data:
    driver: local
