version: '2.2'
services:
  web:
    build: .
    init: true
    entrypoint: []
    command: python manage.py docker_start
    ports:
      - 8000:8000
    links:
      - rabbitmq
      - postgres
      - memcache
    volumes:
      - .:/usr/src/app
      - web-media:/usr/src/app/media
    environment:
      PYTHONUNBUFFERED: 1
      DEBUG: 1
      DATABASE_URL: psql://kompassi:secret@postgres/kompassi
      BROKER_URL: amqp://guest:guest@rabbitmq/
      KOMPAQ_URL: amqp://guest:guest@rabbitmq/
      CACHE_URL: memcache://memcache
      ALLOWED_HOSTS: '*'
  celery:
    build: .
    init: true
    entrypoint: []
    command: celery -A kompassi.celery_app:app worker
    links:
      - rabbitmq
      - postgres
      - memcache
    volumes:
      - .:/usr/src/app:ro
    environment:
      PYTHONUNBUFFERED: 1
      DEBUG: 1
      DATABASE_URL: psql://kompassi:secret@postgres/kompassi
      BROKER_URL: amqp://guest:guest@rabbitmq/
      KOMPAQ_URL: amqp://guest:guest@rabbitmq/
      CACHE_URL: memcache://memcache
  postgres:
    # image: postgres
    build: ./kompassi/sql/
    init: true
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kompassi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kompassi
  rabbitmq:
    image: rabbitmq
    init: true
    ports:
      - 5672:5672
  memcache:
    image: memcached
    init: true

volumes:
  postgres-data: {}
  web-media: {}
