apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    stack: kompassi
    component: rabbitmq
  name: rabbitmq-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
