apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      stack: kompassi
      component: nginx
  template:
    metadata:
      labels:
        stack: kompassi
        component: nginx
    spec:
      containers:
        - name: master
          image: !Var kompassi_static_image
          ports:
            - containerPort: 80
          volumeMounts:
            - !If
                test: !Var kompassi_enable_volumes
                then:
                  mountPath: /usr/share/nginx/html/media
                  name: kompassi-media
      volumes:
        - !If
            test: !Var kompassi_enable_volumes
            then:
              name: kompassi-media
              persistentVolumeClaim:
                claimName: kompassi-media
