apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kompassi
spec:
  rules:
    - host: !Var public_hostname
      http:
        paths:
        - path: /static
          backend:
            serviceName: nginx
            servicePort: 80
        - path: /
          backend:
            serviceName: kompassi
            servicePort: 8000
