apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    stack: kompassi
    component: kompassi
  name: kompassi-media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
